[package]
name = "verify-device-capacity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
crossterm = "0.27"
hex = "0.4"
rand = "0.8"
rand_chacha = "0.3"
sha2 = "0.9"
structopt = "0.3"
